- name: Acte 2 - Configuration
  hosts: csr1000
  gather_facts: false

  tasks:
   - name: config_interfaces
     cisco.ios.ios_l3_interfaces:
       config:
         - name: GigabitEthernet2
           ipv4:
           - address: 192.168.2.1/24
         - name: GigabitEthernet3
           ipv4:
           - address: 192.168.3.1/24
         - name: GigabitEthernet4
           ipv4:
           - address: 192.168.4.1/24
       state: merged

   - name: config_activation_interfaces
     cisco.ios.ios_interfaces:
       config:
         - name: GigabitEthernet1
           enabled: true
         - name: GigabitEthernet1
           enabled: true
         - name: GigabitEthernet1
           enabled: true
         - name: GigabitEthernet1
           enabled: true

   - name: config_dhcp
     cisco.ios.ios_config:
       lines:
       - no ip dhcp pool dhcppool

   - name: config_dhcp2
     cisco.ios.ios_config:
       parents: ["ip dhcp pool dhcppool"]
       lines:
         - "network 192.168.2.0 255.255.255.0"
         - "default-router 192.168.2.1"

   - name: config_nat_outside
     cisco.ios.ios_config:
       parents: 
         - "interface GigabitEthernet1"
       lines:
         - "ip nat outside"

   - name: config_nat_inside
     cisco.ios.ios_config:
       parents: "{{ item }}"
       lines:          
         - "ip nat inside"
     loop:
       - "interface GigabitEthernet2"
       - "interface GigabitEthernet3"
       - "interface GigabitEthernet4"
 
   - name: config_acl
     cisco.ios.ios_config:
       lines:
         - access-list 10 permit 192.168.2.0 0.0.0.255
         - access-list 10 permit 192.168.3.0 0.0.0.255
         - access-list 10 permit 192.168.4.0 0.0.0.255
  
   - name: config_nat
     cisco.ios.ios_config:
       lines:
         - ip nat inside source list 10 interface GigabitEthernet1 overload

   - name: config_pat
     cisco.ios.ios_config:
       lines:
         - ip nat inside source static tcp 192.168.3.2 80 interface GigabitEthernet1 80
         - ip nat inside source static tcp 192.168.4.2 22 interface GigabitEthernet1 2222
